int puertas, ruedas;
string marca,material,color;
bool itv;
float peso, largo;
Console.WriteLine("Ingresar cuantas puertas tiene");
puertas=Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Ingresar cuantas ruedas tiene");
puertas = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Que marca es el auto");
marca=Console.ReadLine();
Console.WriteLine("De que material es el auto");
material =Console.ReadLine();
Console.WriteLine("De que color es el auto");
color=Console.ReadLine();
itv = Convert.ToBoolean(Console.ReadLine());
Console.WriteLine("Cuanto pesa la mesa ");
peso = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Cuanto mide la mesa ");
largo = Convert.ToInt32(Console.ReadLine());